services:
  todolist_database:
    image: postgres:18
    volumes:
      - pgdata_v18:/var/lib/postgresql
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  todolist_app:
    image: todolist_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - todolist_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@todolist_database:5432/app_db

volumes:
  pgdata_v18: